export const ADMIN_WORKSPACE_PERMISSIONS = [
  'USER_LIST',
  'ROLE_LIST',
  'PERMISSION_LIST',
  'LEAD_SOURCE_LIST',
  'AUDIT_LOG_LIST',
  'COMMISSION_PAYMENT_LIST',
  'TARGET_CREATE',
  'USER_CREATE',
] as const;

export const SALES_WORKSPACE_PERMISSIONS = [
  'LEAD_LIST',
  'LEAD_READ',
  'FOLLOW_UP_LIST',
  'FOLLOW_UP_READ',
  'ENROLLMENT_LIST',
  'ENROLLMENT_READ',
  'STUDENT_LIST',
  'STUDENT_READ',
  'PAYMENT_LIST',
  'PAYMENT_READ',
  'TARGET_LIST',
  'TARGET_READ',
  'COMMISSION_LIST',
  'COMMISSION_READ',
  'COURSE_LIST',
  'COURSE_READ',
  'BATCH_LIST',
  'BATCH_READ',
  'INVOICE_LIST',
  'INVOICE_READ',
  'COMMISSION_CREATE',
] as const;

export const DASHBOARD_ACCESS_PERMISSIONS = [
  ...ADMIN_WORKSPACE_PERMISSIONS,
  ...SALES_WORKSPACE_PERMISSIONS,
] as const;
